name: opan
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - scikit-learn
  - scipy
  - sympy
  - pandas
  - seaborn
  - matplotlib
  - pillow=5
  - opencv=3
  - jupyterlab
  - tensorflow
  - keras
  - pydot
  - imagemagick

